@startuml

left to right direction

actor HR as "HR Advisor"
actor DM as "Department Manager"

rectangle "HR System" {
    usecase UC1 as "Produce employee salary report"
    usecase UC2 as "Produce salary report by department"
    usecase UC3 as "Produce salary report of my department"
    usecase UC4 as "Produce salary report by role"
    usecase UCa as "Print salaries"
    usecase UC5 as "View an employee's details"
    usecase UC6 as "Add an employee's details"
}

database DB as "Database"

HR --> UC1
HR --> UC2
HR --> UC4
HR --> UC5
HR --> UC6

DM --> UC3

UC4 ..> UCa : <<include>>

UC1 -- DB
UC2 -- DB
UC3 -- DB
UC4 -- DB
UC5 -- DB
UC6 -- DB

@enduml
